/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as USendRouteImport } from './routes/u/send'
import { Route as USplatRouteImport } from './routes/u/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const USendRoute = USendRouteImport.update({
  id: '/u/send',
  path: '/u/send',
  getParentRoute: () => rootRouteImport,
} as any)
const USplatRoute = USplatRouteImport.update({
  id: '/u/$',
  path: '/u/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/u/$': typeof USplatRoute
  '/u/send': typeof USendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u/$': typeof USplatRoute
  '/u/send': typeof USendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/u/$': typeof USplatRoute
  '/u/send': typeof USendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/u/$' | '/u/send'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/u/$' | '/u/send'
  id: '__root__' | '/' | '/u/$' | '/u/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  USplatRoute: typeof USplatRoute
  USendRoute: typeof USendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/send': {
      id: '/u/send'
      path: '/u/send'
      fullPath: '/u/send'
      preLoaderRoute: typeof USendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$': {
      id: '/u/$'
      path: '/u/$'
      fullPath: '/u/$'
      preLoaderRoute: typeof USplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  USplatRoute: USplatRoute,
  USendRoute: USendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
